clc;
clear;
close all;

% ============================================================
% MATLAB vs VIVADO DWT COEFFICIENT COMPARISON
%
% This script:
%
% 1. Reads the original image
% 2. Calculates MATLAB 5/3 DWT coefficients
% 3. Reads DWT coefficients generated by Vivado
% 4. Compares every coefficient
%
% Vivado files:
%   H_arch.hex
%   L_arch.hex
%   HH_arch.hex
%   HL_arch.hex
%   LH_arch.hex
%   LL_arch.hex
%
% No DWT_reference.mat is required.
%
% ============================================================


%% ============================================================
% 1. IMAGE FILE
% ============================================================

image_file = 'newdog.jpeg';

% Change only this filename for another image.
%
% Example:
% image_file = 'lena.png';
% image_file = 'cameraman.tif';
% image_file = 'test_image.jpg';


%% ============================================================
% 2. READ IMAGE
% ============================================================

img = imread(image_file);


% Convert RGB image to grayscale
if ndims(img) == 3
    img = rgb2gray(img);
end

img = double(img);


% Get image dimensions
IMAGE_ROWS = size(img,1);
IMAGE_COLS = size(img,2);


fprintf('\n');
fprintf('============================================\n');
fprintf(' MATLAB vs VIVADO DWT COMPARISON\n');
fprintf('============================================\n');

fprintf('\nImage: %s\n', image_file);

fprintf('Image size = %d x %d\n', ...
    IMAGE_ROWS, IMAGE_COLS);


%% ============================================================
% 3. CHECK IMAGE SIZE
% ============================================================

% The current DWTarc architecture uses:
%
% IMAGE_ROWS = 300
% IMAGE_COLS = 332
%
% If your Vivado design has been regenerated with different
% parameters, this check will automatically use the image
% dimensions.

if mod(IMAGE_ROWS,2) ~= 0 || mod(IMAGE_COLS,2) ~= 0

    error(['Image dimensions must be even. ', ...
           'Current image = %d x %d'], ...
           IMAGE_ROWS, IMAGE_COLS);

end


HALF_ROWS = IMAGE_ROWS / 2;
HALF_COLS = IMAGE_COLS / 2;


%% ============================================================
% 4. MATLAB HORIZONTAL DWT
% ============================================================

fprintf('\nCalculating MATLAB horizontal DWT...\n');


H = zeros(IMAGE_ROWS, HALF_COLS);
L = zeros(IMAGE_ROWS, HALF_COLS);


for row = 1:IMAGE_ROWS

    % Take one image row
    x = img(row,:);

    % Perform 1-D 5/3 DWT
    [H(row,:), L(row,:)] = dwt53_1d(x);

end


fprintf('H/L calculation complete.\n');


%% ============================================================
% 5. MATLAB VERTICAL DWT
% ============================================================

fprintf('Calculating MATLAB vertical DWT...\n');


% Final subband dimensions
%
% HH = vertical HIGH of H
% HL = vertical LOW  of H
% LH = vertical HIGH of L
% LL = vertical LOW  of L

HH = zeros(HALF_ROWS, HALF_COLS);
HL = zeros(HALF_ROWS, HALF_COLS);

LH = zeros(HALF_ROWS, HALF_COLS);
LL = zeros(HALF_ROWS, HALF_COLS);


for col = 1:HALF_COLS

    % --------------------------------------------------------
    % Vertical DWT of H
    % --------------------------------------------------------

    h_column = H(:,col).';

    [vertical_H, vertical_L] = dwt53_1d(h_column);

    HH(:,col) = vertical_H(:);
    HL(:,col) = vertical_L(:);


    % --------------------------------------------------------
    % Vertical DWT of L
    % --------------------------------------------------------

    l_column = L(:,col).';

    [vertical_H, vertical_L] = dwt53_1d(l_column);

    LH(:,col) = vertical_H(:);
    LL(:,col) = vertical_L(:);

end


fprintf('HH/HL/LH/LL calculation complete.\n');


%% ============================================================
% 6. CONVERT MATLAB MATRICES TO ROW-MAJOR ORDER
%
% MATLAB uses column-major ordering.
%
% Vivado memory files are compared in address order.
%
% Therefore:
%
% matrix.'
%      ↓
% column vector
%
% gives row-major ordering.
% ============================================================

H_ref = H.';
H_ref = H_ref(:);

L_ref = L.';
L_ref = L_ref(:);

HH_ref = HH.';
HH_ref = HH_ref(:);

HL_ref = HL.';
HL_ref = HL_ref(:);

LH_ref = LH.';
LH_ref = LH_ref(:);

LL_ref = LL.';
LL_ref = LL_ref(:);


%% ============================================================
% 7. ROUND MATLAB COEFFICIENTS
% ============================================================

H_ref  = round(H_ref);
L_ref  = round(L_ref);

HH_ref = round(HH_ref);
HL_ref = round(HL_ref);
LH_ref = round(LH_ref);
LL_ref = round(LL_ref);


%% ============================================================
% 8. READ VIVADO OUTPUT FILES
%
% H/L/HH/HL/LH = 16-bit
% LL             = 17-bit
% ============================================================

fprintf('\nReading Vivado output files...\n');


H_arch = read_signed_hex('H_arch.hex',16);

L_arch = read_signed_hex('L_arch.hex',16);

HH_arch = read_signed_hex('HH_arch.hex',16);

HL_arch = read_signed_hex('HL_arch.hex',16);

LH_arch = read_signed_hex('LH_arch.hex',16);

LL_arch = read_signed_hex('LL_arch.hex',17);


fprintf('Vivado files loaded successfully.\n');


%% ============================================================
% 9. EXPECTED COEFFICIENT COUNTS
% ============================================================

EXPECTED_HL_SIZE = IMAGE_ROWS * HALF_COLS;

EXPECTED_FINAL_SIZE = HALF_ROWS * HALF_COLS;


%% ============================================================
% 10. CHECK FILE SIZES
% ============================================================

fprintf('\n');
fprintf('============================================\n');
fprintf('COEFFICIENT COUNTS\n');
fprintf('============================================\n');


fprintf('H  : MATLAB = %d | Vivado = %d\n', ...
    length(H_ref), length(H_arch));

fprintf('L  : MATLAB = %d | Vivado = %d\n', ...
    length(L_ref), length(L_arch));

fprintf('HH : MATLAB = %d | Vivado = %d\n', ...
    length(HH_ref), length(HH_arch));

fprintf('HL : MATLAB = %d | Vivado = %d\n', ...
    length(HL_ref), length(HL_arch));

fprintf('LH : MATLAB = %d | Vivado = %d\n', ...
    length(LH_ref), length(LH_arch));

fprintf('LL : MATLAB = %d | Vivado = %d\n', ...
    length(LL_ref), length(LL_arch));


%% ============================================================
% 11. CHECK THAT MATLAB AND VIVADO SIZES MATCH
% ============================================================

if length(H_ref) ~= length(H_arch)
    error('H coefficient count does not match.');
end

if length(L_ref) ~= length(L_arch)
    error('L coefficient count does not match.');
end

if length(HH_ref) ~= length(HH_arch)
    error('HH coefficient count does not match.');
end

if length(HL_ref) ~= length(HL_arch)
    error('HL coefficient count does not match.');
end

if length(LH_ref) ~= length(LH_arch)
    error('LH coefficient count does not match.');
end

if length(LL_ref) ~= length(LL_arch)
    error('LL coefficient count does not match.');
end


%% ============================================================
% 12. COMPARE EVERY COEFFICIENT
% ============================================================

H_mismatch = find(H_ref ~= H_arch);

L_mismatch = find(L_ref ~= L_arch);

HH_mismatch = find(HH_ref ~= HH_arch);

HL_mismatch = find(HL_ref ~= HL_arch);

LH_mismatch = find(LH_ref ~= LH_arch);

LL_mismatch = find(LL_ref ~= LL_arch);


%% ============================================================
% 13. MISMATCH COUNTS
% ============================================================

H_mismatch_count = length(H_mismatch);

L_mismatch_count = length(L_mismatch);

HH_mismatch_count = length(HH_mismatch);

HL_mismatch_count = length(HL_mismatch);

LH_mismatch_count = length(LH_mismatch);

LL_mismatch_count = length(LL_mismatch);


%% ============================================================
% 14. MATCH COUNTS
% ============================================================

H_match_count = length(H_ref) - H_mismatch_count;

L_match_count = length(L_ref) - L_mismatch_count;

HH_match_count = length(HH_ref) - HH_mismatch_count;

HL_match_count = length(HL_ref) - HL_mismatch_count;

LH_match_count = length(LH_ref) - LH_mismatch_count;

LL_match_count = length(LL_ref) - LL_mismatch_count;


%% ============================================================
% 15. MATCHING PERCENTAGES
% ============================================================

H_percentage = ...
    H_match_count / length(H_ref) * 100;

L_percentage = ...
    L_match_count / length(L_ref) * 100;

HH_percentage = ...
    HH_match_count / length(HH_ref) * 100;

HL_percentage = ...
    HL_match_count / length(HL_ref) * 100;

LH_percentage = ...
    LH_match_count / length(LH_ref) * 100;

LL_percentage = ...
    LL_match_count / length(LL_ref) * 100;


%% ============================================================
% 16. DISPLAY RESULTS FOR EACH BAND
% ============================================================

fprintf('\n');
fprintf('============================================\n');
fprintf('BAND-BY-BAND RESULTS\n');
fprintf('============================================\n');


fprintf('\nH:\n');
fprintf('  Matches    = %d / %d\n', ...
    H_match_count, length(H_ref));

fprintf('  Mismatches = %d / %d\n', ...
    H_mismatch_count, length(H_ref));

fprintf('  Matching   = %.2f%%\n', ...
    H_percentage);


fprintf('\nL:\n');
fprintf('  Matches    = %d / %d\n', ...
    L_match_count, length(L_ref));

fprintf('  Mismatches = %d / %d\n', ...
    L_mismatch_count, length(L_ref));

fprintf('  Matching   = %.2f%%\n', ...
    L_percentage);


fprintf('\nHH:\n');
fprintf('  Matches    = %d / %d\n', ...
    HH_match_count, length(HH_ref));

fprintf('  Mismatches = %d / %d\n', ...
    HH_mismatch_count, length(HH_ref));

fprintf('  Matching   = %.2f%%\n', ...
    HH_percentage);


fprintf('\nHL:\n');
fprintf('  Matches    = %d / %d\n', ...
    HL_match_count, length(HL_ref));

fprintf('  Mismatches = %d / %d\n', ...
    HL_mismatch_count, length(HL_ref));

fprintf('  Matching   = %.2f%%\n', ...
    HL_percentage);


fprintf('\nLH:\n');
fprintf('  Matches    = %d / %d\n', ...
    LH_match_count, length(LH_ref));

fprintf('  Mismatches = %d / %d\n', ...
    LH_mismatch_count, length(LH_ref));

fprintf('  Matching   = %.2f%%\n', ...
    LH_percentage);


fprintf('\nLL:\n');
fprintf('  Matches    = %d / %d\n', ...
    LL_match_count, length(LL_ref));

fprintf('  Mismatches = %d / %d\n', ...
    LL_mismatch_count, length(LL_ref));

fprintf('  Matching   = %.2f%%\n', ...
    LL_percentage);


%% ============================================================
% 17. FINAL SUBBAND VERIFICATION
%
% Only HH + HL + LH + LL
%
% 4 x 24,900 = 99,600 coefficients
% ============================================================

FINAL_TOTAL = ...
    length(HH_ref) + ...
    length(HL_ref) + ...
    length(LH_ref) + ...
    length(LL_ref);


FINAL_MISMATCHES = ...
    HH_mismatch_count + ...
    HL_mismatch_count + ...
    LH_mismatch_count + ...
    LL_mismatch_count;


FINAL_MATCHES = ...
    FINAL_TOTAL - FINAL_MISMATCHES;


FINAL_PERCENTAGE = ...
    FINAL_MATCHES / FINAL_TOTAL * 100;


fprintf('\n');
fprintf('============================================\n');
fprintf('FINAL SUBBAND RESULT\n');
fprintf('============================================\n');

fprintf('Total coefficients = %d\n', ...
    FINAL_TOTAL);

fprintf('Total matches      = %d\n', ...
    FINAL_MATCHES);

fprintf('Total mismatches   = %d\n', ...
    FINAL_MISMATCHES);

fprintf('Matching percentage = %.2f%%\n', ...
    FINAL_PERCENTAGE);


%% ============================================================
% 18. FIRST MISMATCH OF EACH BAND
% ============================================================

fprintf('\n');
fprintf('============================================\n');
fprintf('FIRST MISMATCH IN EACH BAND\n');
fprintf('============================================\n');


if isempty(H_mismatch)

    fprintf('\nH: No mismatch\n');

else

    k = H_mismatch(1);

    fprintf('\nH:\n');
    fprintf('Index  = %d\n',k);
    fprintf('MATLAB = %d\n',H_ref(k));
    fprintf('Vivado = %d\n',H_arch(k));

end


if isempty(L_mismatch)

    fprintf('\nL: No mismatch\n');

else

    k = L_mismatch(1);

    fprintf('\nL:\n');
    fprintf('Index  = %d\n',k);
    fprintf('MATLAB = %d\n',L_ref(k));
    fprintf('Vivado = %d\n',L_arch(k));

end


if isempty(HH_mismatch)

    fprintf('\nHH: No mismatch\n');

else

    k = HH_mismatch(1);

    fprintf('\nHH:\n');
    fprintf('Index  = %d\n',k);
    fprintf('MATLAB = %d\n',HH_ref(k));
    fprintf('Vivado = %d\n',HH_arch(k));

end


if isempty(HL_mismatch)

    fprintf('\nHL: No mismatch\n');

else

    k = HL_mismatch(1);

    fprintf('\nHL:\n');
    fprintf('Index  = %d\n',k);
    fprintf('MATLAB = %d\n',HL_ref(k));
    fprintf('Vivado = %d\n',HL_arch(k));

end


if isempty(LH_mismatch)

    fprintf('\nLH: No mismatch\n');

else

    k = LH_mismatch(1);

    fprintf('\nLH:\n');
    fprintf('Index  = %d\n',k);
    fprintf('MATLAB = %d\n',LH_ref(k));
    fprintf('Vivado = %d\n',LH_arch(k));

end


if isempty(LL_mismatch)

    fprintf('\nLL: No mismatch\n');

else

    k = LL_mismatch(1);

    fprintf('\nLL:\n');
    fprintf('Index  = %d\n',k);
    fprintf('MATLAB = %d\n',LL_ref(k));
    fprintf('Vivado = %d\n',LL_arch(k));

end


%% ============================================================
% 19. FIRST 10 VALUES
% ============================================================

fprintf('\n');
fprintf('============================================\n');
fprintf('FIRST 10 VALUES\n');
fprintf('============================================\n');


fprintf('\nH:\n');
fprintf('MATLAB: ');
disp(H_ref(1:10).');

fprintf('Vivado: ');
disp(H_arch(1:10).');


fprintf('\nL:\n');
fprintf('MATLAB: ');
disp(L_ref(1:10).');

fprintf('Vivado: ');
disp(L_arch(1:10).');


fprintf('\nHH:\n');
fprintf('MATLAB: ');
disp(HH_ref(1:10).');

fprintf('Vivado: ');
disp(HH_arch(1:10).');


fprintf('\nHL:\n');
fprintf('MATLAB: ');
disp(HL_ref(1:10).');

fprintf('Vivado: ');
disp(HL_arch(1:10).');


fprintf('\nLH:\n');
fprintf('MATLAB: ');
disp(LH_ref(1:10).');

fprintf('Vivado: ');
disp(LH_arch(1:10).');


fprintf('\nLL:\n');
fprintf('MATLAB: ');
disp(LL_ref(1:10).');

fprintf('Vivado: ');
disp(LL_arch(1:10).');


%% ============================================================
% FUNCTION 1:
% 1-D 5/3 DWT
%
% High-pass:
%
% H[n] = -x[2n-1]
%        +2*x[2n]
%        -x[2n+1]
%
%
% Low-pass:
%
% L[n] = -x[2n-1]
%        +2*x[2n]
%        +6*x[2n+1]
%        +2*x[2n+2]
%        -x[2n+3]
%
% Boundary convention:
%
% x[-1] = x[1]
% x[N]  = x[N-2]
% x[N+1] = x[N-3]
%
% ============================================================

function [H,L] = dwt53_1d(x)

    N = length(x);

    if mod(N,2) ~= 0

        error('DWT input length must be even.');

    end

    HALF = N/2;

    H = zeros(1,HALF);

    L = zeros(1,HALF);


    for n = 0:HALF-1

        % ----------------------------------------------------
        % HIGH-PASS
        % ----------------------------------------------------

        % x[2n-1]
        if n == 0

            xm1 = x(2);

        else

            xm1 = x(2*n);

        end


        % x[2n]
        x0 = x(2*n + 1);


        % x[2n+1]
        if (2*n + 1) >= N

            xp1 = x(N-1);

        else

            xp1 = x(2*n + 2);

        end


        H(n+1) = ...
            -xm1 ...
            +2*x0 ...
            -xp1;


        % ----------------------------------------------------
        % LOW-PASS
        % ----------------------------------------------------

        % x[2n-1]
        if n == 0

            xm1 = x(3);

        else

            xm1 = x(2*n);

        end


        % x[2n]
        x0 = x(2*n + 1);


        % x[2n+1]
        xp1 = x(2*n + 2);


        % x[2n+2]
        if (2*n + 2) >= N

            xp2 = x(N-1);

        else

            xp2 = x(2*n + 3);

        end


        % x[2n+3]
        if (2*n + 3) >= N

            xp3 = x(N-2);

        else

            xp3 = x(2*n + 4);

        end


        L(n+1) = ...
            -xm1 ...
            +2*x0 ...
            +6*xp1 ...
            +2*xp2 ...
            -xp3;

    end

end


%% ============================================================
% FUNCTION 2:
% READ SIGNED HEX
%
% bits = 16 for:
%   H, L, HH, HL, LH
%
% bits = 17 for:
%   LL
%
% ============================================================

function y = read_signed_hex(filename,bits)

    fid = fopen(filename,'r');

    if fid == -1

        error('Could not open file: %s',filename);

    end


    data = textscan(fid,'%s');

    fclose(fid);


    hex_data = data{1};


    % HEX → unsigned value

    u = hex2dec(hex_data);


    % Two's-complement conversion

    threshold = 2^(bits-1);

    modulus = 2^bits;


    u(u >= threshold) = ...
        u(u >= threshold) - modulus;


    y = double(u);

    y = y(:);

end